# Generated by Django 5.2 on 2025-05-17 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0002_businesssponsorshipform_creditanalysisform_and_more'),
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApprovalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_approval_forms', to='credit_applications.creditapplication')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_approval_forms', to='workflow_engine.workflowinstance')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCompilationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_compilation_forms', to='credit_applications.creditapplication')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_compilation_forms', to='workflow_engine.workflowinstance')),
            ],
        ),
    ]
