# Generated by Django 5.2.1 on 2025-05-18 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0003_creditapprovalform_creditcompilationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='description',
            new_name='business_description',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='identifier',
            new_name='cif_number',
        ),
        migrations.RenameField(
            model_name='limitrequest',
            old_name='rationale',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='limitrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='limitrequest',
            name='currency',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='adaptiv_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='country_of_incorporation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='credit_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='crs_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='fitch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='industry_subsector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='kyc_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='legal_entity_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='relationship_manager_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='relationship_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='senior_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='spreadpac_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='assigned_to',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='decision_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='risk_assessment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='risk_assessment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='limitrequest',
            name='existing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='limitrequest',
            name='existing_tenor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitrequest',
            name='proposed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='limitrequest',
            name='proposed_tenor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitrequest',
            name='limit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credit_applications.limittype'),
        ),
    ]
