# Generated by Django 5.2.1 on 2025-05-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0005_seed_limittypes_and_counterparties'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequestform',
            name='account_executive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='country_risk_limit_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='financial_statements_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='guarantor_cif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='high_priority_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='interim_statements_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='kyc_approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='last_client_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='legal_documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='most_senior_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='positive_legal_opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='projected_rorwa_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='relationship_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='revenue_last_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='revenue_projected_12m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='second_business_sponsor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='senior_business_sponsor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed comments on limits required'),
        ),
        migrations.AlterField(
            model_name='creditrequestform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_request_form', to='credit_applications.creditapplication'),
        ),
    ]
