# Generated by Django 5.2.1 on 2025-06-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0006_creditrequestform_account_executive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequestform',
            name='counterparty_cif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_sponsorship_form', to='credit_applications.creditapplication'),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_questionnaire_form', to='credit_applications.creditapplication'),
        ),
        migrations.AlterField(
            model_name='creditreviewform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_review_form', to='credit_applications.creditapplication'),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_review_form', to='credit_applications.creditapplication'),
        ),
    ]
