# Generated by Django 5.2.1 on 2025-06-08 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0007_creditrequestform_counterparty_cif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditrequestform',
            old_name='second_business_sponsor',
            new_name='second_business_sponsor_name',
        ),
        migrations.RemoveField(
            model_name='creditrequestform',
            name='senior_business_sponsor',
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='second_business_sponsor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crf_second_sponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='senior_business_sponsor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crf_senior_sponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='senior_business_sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
