# Generated by Django 5.2.1 on 2025-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0010_businesssponsorshipform_form_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequestform',
            name='form_data',
        ),
    ]
