# Generated by Django 5.2.1 on 2025-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0012_alter_creditapplication_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequestform',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=255, null=True, help_text='Denormalized field for counterparty name'),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='relationship_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True, help_text='Denormalized field for relationship manager name'),
        ),
        migrations.AddField(
            model_name='creditrequestform',
            name='detailed_limit_comments',
            field=models.TextField(blank=True, null=True, help_text='Denormalized field for detailed limit comments'),
        ),
    ]
