# Generated by Django 5.2.1 on 2025-06-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0013_auto_20250620_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, help_text='Relationship manager responsible for this credit application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_credit_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
