# Generated by Django 5.2.1 on 2025-06-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0014_creditapplication_relationship_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssponsorshipform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='creditanalysisform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='creditapprovalform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='creditcompilationform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='creditreviewform',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='legalreviewform',
            name='form_data',
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='second_business_sponsor',
            field=models.ForeignKey(blank=True, help_text='Optional second Business Sponsor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_sponsored_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='second_business_sponsor_name',
            field=models.CharField(blank=True, help_text='Denormalized name of second business sponsor', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='second_sponsor_approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Second sponsor approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='second_sponsor_comments',
            field=models.TextField(blank=True, help_text='Second sponsor comments on their decision'),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='senior_business_sponsor',
            field=models.ForeignKey(blank=True, help_text='Senior Business Sponsor (from Credit Request)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='senior_business_sponsor_name',
            field=models.CharField(blank=True, help_text='Denormalized name of senior business sponsor', max_length=255),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='senior_sponsor_approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Senior sponsor approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='businesssponsorshipform',
            name='senior_sponsor_comments',
            field=models.TextField(blank=True, help_text='Senior sponsor comments on their decision'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='business_model_assessment',
            field=models.TextField(blank=True, help_text='Assessment of business model and strategy'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='cash_flow_analysis',
            field=models.TextField(blank=True, help_text='Cash flow analysis and projections'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='climate_risk_score',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Climate risk assessment score', max_length=10),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='credit_analyst',
            field=models.ForeignKey(blank=True, help_text='Credit Analyst performing the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='credit_rating_recommendation',
            field=models.CharField(blank=True, help_text='Internal credit rating recommendation', max_length=10),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='debt_capacity_analysis',
            field=models.TextField(blank=True, help_text='Assessment of debt capacity and leverage'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='esg_score',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='ESG risk score', max_length=10),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='Executive summary of the credit analysis'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='industry_analysis',
            field=models.TextField(blank=True, help_text='Industry analysis and outlook'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='key_risks',
            field=models.TextField(blank=True, help_text='Key risks identified'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='loss_given_default',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated loss given default (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='management_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor')], help_text='Management quality assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='mitigating_factors',
            field=models.TextField(blank=True, help_text='Mitigating factors and risk controls'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='physical_risk_assessment',
            field=models.TextField(blank=True, help_text='Assessment of physical climate risks'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='probability_of_default',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated probability of default (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='profitability_analysis',
            field=models.TextField(blank=True, help_text='Analysis of profitability metrics'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('approve_with_conditions', 'Approve with Conditions'), ('reject', 'Reject')], help_text='Final recommendation', max_length=25),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='recommended_conditions',
            field=models.TextField(blank=True, help_text='Recommended conditions if applicable'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='revenue_analysis',
            field=models.TextField(blank=True, help_text='Analysis of revenue trends and sustainability'),
        ),
        migrations.AddField(
            model_name='creditanalysisform',
            name='transition_risk_assessment',
            field=models.TextField(blank=True, help_text='Assessment of transition risks'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Comments and rationale for the approval decision'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approval_conditions',
            field=models.TextField(blank=True, help_text='Conditions precedent and subsequent to approval'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of approval decision', null=True),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approval_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], help_text='Final approval decision', max_length=25),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total approved amount across all facilities', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Credit Committee member or DA holder who made the approval decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='committee_meeting_date',
            field=models.DateField(blank=True, help_text='Date of credit committee meeting (if DA level requires CC)', null=True),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='committee_members_present',
            field=models.TextField(blank=True, help_text='Names of credit committee members present at the meeting'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='covenants',
            field=models.TextField(blank=True, help_text='Financial and operational covenants'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='delegated_authority_level',
            field=models.CharField(blank=True, choices=[('DA1', 'DA1'), ('DA2', 'DA2'), ('DA3', 'DA3'), ('DA4', 'DA4'), ('DA5', 'DA5'), ('DA6', 'DA6'), ('DA7', 'DA7'), ('DA8', 'DA8'), ('CC', 'Credit Committee')], help_text='Delegated authority level used for approval', max_length=10),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='documentation_requirements',
            field=models.TextField(blank=True, help_text='Legal documentation requirements for drawdown'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date of the approval', null=True),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='facility_terms',
            field=models.TextField(blank=True, help_text='Key terms and conditions of approved facilities'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='pricing_terms',
            field=models.TextField(blank=True, help_text='Approved pricing and fee structure'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='review_date',
            field=models.DateField(blank=True, help_text='Next review date for the approved facilities', null=True),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='risk_assessment_summary',
            field=models.TextField(blank=True, help_text='Summary of key risks and mitigants considered'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='special_conditions',
            field=models.TextField(blank=True, help_text='Any special conditions or requirements'),
        ),
        migrations.AddField(
            model_name='creditapprovalform',
            name='tenor_approved',
            field=models.IntegerField(blank=True, help_text='Approved tenor in months', null=True),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='all_forms_reviewed',
            field=models.BooleanField(default=False, help_text='All required forms have been reviewed'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='business_rationale',
            field=models.TextField(blank=True, help_text='Business rationale for the facilities'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='compiler',
            field=models.ForeignKey(blank=True, help_text='Credit Analyst who compiled the credit paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_credit_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='compiler_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the compiler'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='conditions_precedent',
            field=models.TextField(blank=True, help_text='Conditions precedent to drawdown'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='counterparty_background',
            field=models.TextField(blank=True, help_text='Background information on counterparty'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='credit_paper_summary',
            field=models.TextField(blank=True, help_text='Executive summary of the credit paper'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='facility_summary',
            field=models.TextField(blank=True, help_text='Summary of requested facilities'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='financial_analysis_summary',
            field=models.TextField(blank=True, help_text='Summary of financial analysis'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='legal_documentation_summary',
            field=models.TextField(blank=True, help_text='Summary of legal documentation review'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='ongoing_covenants',
            field=models.TextField(blank=True, help_text='Ongoing covenants and monitoring requirements'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='pricing_summary',
            field=models.TextField(blank=True, help_text='Pricing and fee structure summary'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='ready_for_approval',
            field=models.BooleanField(default=False, help_text='Credit paper is ready for approval'),
        ),
        migrations.AddField(
            model_name='creditcompilationform',
            name='risk_assessment_summary',
            field=models.TextField(blank=True, help_text='Summary of risk assessment findings'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Any additional relevant information'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='business_purpose',
            field=models.TextField(blank=True, help_text='Primary business purpose of the credit facility'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='collateral_details',
            field=models.TextField(blank=True, help_text='Details of any collateral offered'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='environmental_details',
            field=models.TextField(blank=True, help_text='Details of environmental liabilities if any'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='environmental_liabilities',
            field=models.BooleanField(blank=True, help_text='Any known environmental liabilities', null=True),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='existing_debt_facilities',
            field=models.TextField(blank=True, help_text='Details of existing debt facilities'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='fund_utilization',
            field=models.TextField(blank=True, help_text='How will the funds be utilized'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='litigation_details',
            field=models.TextField(blank=True, help_text='Details of litigation if any'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='litigation_proceedings',
            field=models.BooleanField(blank=True, help_text='Any ongoing litigation proceedings', null=True),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='material_changes_since_financials',
            field=models.TextField(blank=True, help_text='Material changes since last financial statements'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='other_banking_relationships',
            field=models.TextField(blank=True, help_text='Other significant banking relationships'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='questionnaire_completor',
            field=models.ForeignKey(blank=True, help_text='Relationship Manager who completed the questionnaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='regulatory_investigations',
            field=models.BooleanField(blank=True, help_text='Any ongoing regulatory investigations', null=True),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='regulatory_investigations_details',
            field=models.TextField(blank=True, help_text='Details of regulatory investigations if any'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='repayment_source',
            field=models.TextField(blank=True, help_text='Primary source of repayment'),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='additional_information_request',
            field=models.TextField(blank=True, help_text='Request for additional information from Front Office'),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='assigned_credit_analyst',
            field=models.ForeignKey(blank=True, help_text='Credit Analyst assigned to perform the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_for_analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='credit_reviewer',
            field=models.ForeignKey(blank=True, help_text='Credit Analyst responsible for this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='delegated_authority_level',
            field=models.CharField(blank=True, choices=[('DA1', 'DA1'), ('DA2', 'DA2'), ('DA3', 'DA3'), ('DA4', 'DA4'), ('DA5', 'DA5'), ('DA6', 'DA6'), ('DA7', 'DA7'), ('DA8', 'DA8')], help_text='Required delegated authority level for approval', max_length=10),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='questionnaire_required',
            field=models.BooleanField(default=False, help_text='Whether additional Credit Questionnaire is required'),
        ),
        migrations.AddField(
            model_name='creditreviewform',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if application is rejected'),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='agreement_template',
            field=models.CharField(blank=True, help_text='Agreement template used (e.g., ISDA, CSA)', max_length=100),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='counterparty_events_of_default',
            field=models.TextField(blank=True, help_text='Counterparty events of default provisions'),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='csa_independent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CSA independent amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='csa_minimum_transfer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CSA minimum transfer amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='csa_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CSA threshold amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='csa_type',
            field=models.CharField(blank=True, help_text='Type of CSA agreement', max_length=50),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='governing_law',
            field=models.CharField(blank=True, help_text='Governing law for the agreement', max_length=100),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='grace_period',
            field=models.CharField(blank=True, help_text='Grace period for defaults', max_length=100),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='has_csa',
            field=models.BooleanField(blank=True, help_text='Whether CSA is in place', null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='iosco_compliant',
            field=models.BooleanField(blank=True, help_text='IOSCO compliance status', null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='legal_reviewer',
            field=models.ForeignKey(blank=True, help_text='Legal Reviewer responsible for this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='non_standard_provisions',
            field=models.TextField(blank=True, help_text='Any non-standard provisions in the agreement'),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='positive_collateral_opinion',
            field=models.BooleanField(blank=True, help_text='Positive collateral opinion received', null=True),
        ),
        migrations.AddField(
            model_name='legalreviewform',
            name='positive_netting_opinion',
            field=models.BooleanField(blank=True, help_text='Positive netting opinion received', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_analysis_form', to='credit_applications.creditapplication'),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_approval_form', to='credit_applications.creditapplication'),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='credit_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_compilation_form', to='credit_applications.creditapplication'),
        ),
    ]
