# Generated by Django 5.2.1 on 2025-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0015_remove_businesssponsorshipform_form_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='business_purpose',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='collateral_details',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='environmental_details',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='environmental_liabilities',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='existing_debt_facilities',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='fund_utilization',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='litigation_details',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='litigation_proceedings',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='material_changes_since_financials',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='other_banking_relationships',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='regulatory_investigations',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='regulatory_investigations_details',
        ),
        migrations.RemoveField(
            model_name='creditquestionnaireform',
            name='repayment_source',
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='available_derivative_lines',
            field=models.TextField(blank=True, help_text='What are their total available derivative lines?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='business_model_description',
            field=models.TextField(blank=True, help_text='Basic details of counterparty business model (what do they do, how do they make money?)'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='cash_banking_lines',
            field=models.TextField(blank=True, help_text='What available cash and banking lines (committed & uncommitted) does the client have available? How much is unutilized?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='china_parent_restrictions',
            field=models.TextField(blank=True, help_text='For entities reliant on a nonshore China parent, give details of USD cash position/terms/restrictions'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='exit_risk_limits',
            field=models.TextField(blank=True, help_text='Size of exit risk limits in place and assumed exit tenor?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='hedge_accounting',
            field=models.TextField(blank=True, help_text='Is hedge accounting (IFRS 9 or ASC 815) applied to the metal hedges? Cash flow or fair value hedges?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='icbcs_financing',
            field=models.TextField(blank=True, help_text='Size ($ and equivalent volume) of ICBCS financing line?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='icbcs_proportion_total_book',
            field=models.TextField(blank=True, help_text='Approximately what proportion of their total metals trading or hedge book could ICBCS account for?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='key_suppliers_customers',
            field=models.TextField(blank=True, help_text='Key suppliers and/or customers, typical terms of trade or credit provided to customers'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='location_grade_details',
            field=models.TextField(blank=True, help_text='Metal, material grade (e.g., LGD) and financing locus for each transit?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='margining_vs_unmargined',
            field=models.TextField(blank=True, help_text='Are all hedging facilities subject to margining or are unmargined OTC lines also provided?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='market_stress_tests',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('yes', 'Yes'), ('no', 'No')], help_text='Does the counterparty run market stress tests?', max_length=10),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='material_basis_risk',
            field=models.TextField(blank=True, help_text='What is the volume/value of any material basis risk that the counterparty cannot hedge?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='notional_value_requested',
            field=models.TextField(blank=True, help_text='What notional value do the requested IMPL or PFE lines rise to at current prices?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='other_counterparties_count',
            field=models.IntegerField(blank=True, help_text='How many other counterparties does the client use?', null=True),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='other_secured_trade_finance',
            field=models.TextField(blank=True, help_text='Any other secured trade finance used by client?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='position_business_context',
            field=models.TextField(blank=True, help_text='Does that make sense in context of their underlying business?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='position_size_drivers',
            field=models.TextField(blank=True, help_text='What determines the size/type of positions taken?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='primary_products',
            field=models.TextField(blank=True, help_text='What metals/products do they trade primarily (e.g., LME outrights, OTC averages, loco London gold)?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='repo_balance_sheet_treatment',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('on_balance_sheet', 'On balance sheet secured financing'), ('off_balance_sheet', 'Off balance sheet')], help_text='Balance sheet treatment of repos', max_length=50),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='repo_hedging_management',
            field=models.TextField(blank=True, help_text='How does the facility basis close the client and ICBCS manage hedging of the metal financed under repo?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='strategic_vs_proprietary',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('strategic', 'Strategic Hedging'), ('proprietary', 'Proprietary Trading'), ('both', 'Both')], help_text='Does the counterparty engage in strategic hedging or proprietary trading?', max_length=50),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='stress_assumptions',
            field=models.TextField(blank=True, help_text='What are the stress assumptions?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='stress_governance',
            field=models.TextField(blank=True, help_text='Who sets/governs the stress/VaR levels?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='stress_management',
            field=models.TextField(blank=True, help_text='How do the results inform cash/liquid assets or risk management actions?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='total_counterparty_financing_lines',
            field=models.TextField(blank=True, help_text="Size ($ and volume) of client's total metal financing lines with all counterparties?"),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='total_position_capacity',
            field=models.TextField(blank=True, help_text='Including limits at other banks or brokers, what is the total size of position in oz/tonnes and USD they can run?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='trading_flow_drivers',
            field=models.TextField(blank=True, help_text="What is that trading flow driven by (e.g., hedging inventory or OPs, their own clients' trading flows)?"),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='trading_policy_governance',
            field=models.TextField(blank=True, help_text='Who determines trading/hedge policies (e.g., Board)?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='treasury_management_structure',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('centralized', 'Centralized'), ('entity_level', 'At entity level')], help_text='For groups with multiple entities, treasury and liquidity management structure', max_length=50),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='typical_max_tenor',
            field=models.TextField(blank=True, help_text='Typical and maximum expected tenor of trades and/or hedges for each metal?'),
        ),
        migrations.AddField(
            model_name='creditquestionnaireform',
            name='usd_cash_location',
            field=models.TextField(blank=True, help_text='Where is USD cash available for margin calls held and managed from?'),
        ),
    ]
