# Generated by Django 5.2.1 on 2025-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0016_restructure_credit_questionnaire_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapprovalform',
            name='committee_members_present',
            field=models.TextField(blank=True, help_text='Names of credit committee members present at the meeting', null=True),
        ),
    ]
