# Generated by Django 5.2.1 on 2025-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0017_fix_committee_members_present_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapprovalform',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Comments and rationale for the approval decision', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='approval_conditions',
            field=models.TextField(blank=True, help_text='Conditions precedent and subsequent to approval', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='approval_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], help_text='Final approval decision', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='covenants',
            field=models.TextField(blank=True, help_text='Financial and operational covenants', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='delegated_authority_level',
            field=models.CharField(blank=True, choices=[('DA1', 'DA1'), ('DA2', 'DA2'), ('DA3', 'DA3'), ('DA4', 'DA4'), ('DA5', 'DA5'), ('DA6', 'DA6'), ('DA7', 'DA7'), ('DA8', 'DA8'), ('CC', 'Credit Committee')], help_text='Delegated authority level used for approval', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='documentation_requirements',
            field=models.TextField(blank=True, help_text='Legal documentation requirements for drawdown', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='facility_terms',
            field=models.TextField(blank=True, help_text='Key terms and conditions of approved facilities', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='pricing_terms',
            field=models.TextField(blank=True, help_text='Approved pricing and fee structure', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='risk_assessment_summary',
            field=models.TextField(blank=True, help_text='Summary of key risks and mitigants considered', null=True),
        ),
        migrations.AlterField(
            model_name='creditapprovalform',
            name='special_conditions',
            field=models.TextField(blank=True, help_text='Any special conditions or requirements', null=True),
        ),
    ]
