# Generated by Django 5.2.1 on 2025-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0018_fix_credit_approval_form_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditreviewform',
            name='additional_information_request',
            field=models.TextField(blank=True, help_text='Request for additional information from Front Office', null=True),
        ),
        migrations.AlterField(
            model_name='creditreviewform',
            name='delegated_authority_level',
            field=models.CharField(blank=True, choices=[('DA1', 'DA1'), ('DA2', 'DA2'), ('DA3', 'DA3'), ('DA4', 'DA4'), ('DA5', 'DA5'), ('DA6', 'DA6'), ('DA7', 'DA7'), ('DA8', 'DA8')], help_text='Required delegated authority level for approval', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditreviewform',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if application is rejected', null=True),
        ),
    ]
