# Generated by Django 5.2.1 on 2025-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0019_fix_credit_review_form_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='second_business_sponsor_name',
            field=models.CharField(blank=True, help_text='Denormalized name of second business sponsor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='second_sponsor_approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Second sponsor approval decision', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='second_sponsor_comments',
            field=models.TextField(blank=True, help_text='Second sponsor comments on their decision', null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='senior_business_sponsor_name',
            field=models.CharField(blank=True, help_text='Denormalized name of senior business sponsor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='senior_sponsor_approval',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Senior sponsor approval decision', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesssponsorshipform',
            name='senior_sponsor_comments',
            field=models.TextField(blank=True, help_text='Senior sponsor comments on their decision', null=True),
        ),
    ]
