# Generated by Django 5.2.1 on 2025-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0020_fix_business_sponsorship_form_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='available_derivative_lines',
            field=models.TextField(blank=True, help_text='What are their total available derivative lines?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='business_model_description',
            field=models.TextField(blank=True, help_text='Basic details of counterparty business model (what do they do, how do they make money?)', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='cash_banking_lines',
            field=models.TextField(blank=True, help_text='What available cash and banking lines (committed & uncommitted) does the client have available? How much is unutilized?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='china_parent_restrictions',
            field=models.TextField(blank=True, help_text='For entities reliant on a nonshore China parent, give details of USD cash position/terms/restrictions', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='exit_risk_limits',
            field=models.TextField(blank=True, help_text='Size of exit risk limits in place and assumed exit tenor?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='hedge_accounting',
            field=models.TextField(blank=True, help_text='Is hedge accounting (IFRS 9 or ASC 815) applied to the metal hedges? Cash flow or fair value hedges?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='icbcs_financing',
            field=models.TextField(blank=True, help_text='Size ($ and equivalent volume) of ICBCS financing line?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='icbcs_proportion_total_book',
            field=models.TextField(blank=True, help_text='Approximately what proportion of their total metals trading or hedge book could ICBCS account for?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='key_suppliers_customers',
            field=models.TextField(blank=True, help_text='Key suppliers and/or customers, typical terms of trade or credit provided to customers', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='location_grade_details',
            field=models.TextField(blank=True, help_text='Metal, material grade (e.g., LGD) and financing locus for each transit?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='margining_vs_unmargined',
            field=models.TextField(blank=True, help_text='Are all hedging facilities subject to margining or are unmargined OTC lines also provided?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='market_stress_tests',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('yes', 'Yes'), ('no', 'No')], help_text='Does the counterparty run market stress tests?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='material_basis_risk',
            field=models.TextField(blank=True, help_text='What is the volume/value of any material basis risk that the counterparty cannot hedge?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='notional_value_requested',
            field=models.TextField(blank=True, help_text='What notional value do the requested IMPL or PFE lines rise to at current prices?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='other_secured_trade_finance',
            field=models.TextField(blank=True, help_text='Any other secured trade finance used by client?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='position_business_context',
            field=models.TextField(blank=True, help_text='Does that make sense in context of their underlying business?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='position_size_drivers',
            field=models.TextField(blank=True, help_text='What determines the size/type of positions taken?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='primary_products',
            field=models.TextField(blank=True, help_text='What metals/products do they trade primarily (e.g., LME outrights, OTC averages, loco London gold)?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='repo_balance_sheet_treatment',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('on_balance_sheet', 'On balance sheet secured financing'), ('off_balance_sheet', 'Off balance sheet')], help_text='Balance sheet treatment of repos', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='repo_hedging_management',
            field=models.TextField(blank=True, help_text='How does the facility basis close the client and ICBCS manage hedging of the metal financed under repo?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='strategic_vs_proprietary',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('strategic', 'Strategic Hedging'), ('proprietary', 'Proprietary Trading'), ('both', 'Both')], help_text='Does the counterparty engage in strategic hedging or proprietary trading?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='stress_assumptions',
            field=models.TextField(blank=True, help_text='What are the stress assumptions?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='stress_governance',
            field=models.TextField(blank=True, help_text='Who sets/governs the stress/VaR levels?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='stress_management',
            field=models.TextField(blank=True, help_text='How do the results inform cash/liquid assets or risk management actions?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='total_counterparty_financing_lines',
            field=models.TextField(blank=True, help_text="Size ($ and volume) of client's total metal financing lines with all counterparties?", null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='total_position_capacity',
            field=models.TextField(blank=True, help_text='Including limits at other banks or brokers, what is the total size of position in oz/tonnes and USD they can run?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='trading_flow_drivers',
            field=models.TextField(blank=True, help_text="What is that trading flow driven by (e.g., hedging inventory or OPs, their own clients' trading flows)?", null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='trading_policy_governance',
            field=models.TextField(blank=True, help_text='Who determines trading/hedge policies (e.g., Board)?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='treasury_management_structure',
            field=models.CharField(blank=True, choices=[('', 'Select option'), ('centralized', 'Centralized'), ('entity_level', 'At entity level')], help_text='For groups with multiple entities, treasury and liquidity management structure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='typical_max_tenor',
            field=models.TextField(blank=True, help_text='Typical and maximum expected tenor of trades and/or hedges for each metal?', null=True),
        ),
        migrations.AlterField(
            model_name='creditquestionnaireform',
            name='usd_cash_location',
            field=models.TextField(blank=True, help_text='Where is USD cash available for margin calls held and managed from?', null=True),
        ),
    ]
