# Generated by Django 6.0 on 2025-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0021_fix_credit_questionnaire_form_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequestform',
            name='high_priority_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
