# Generated by Django 5.2.1 on 2025-12-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0022_allow_null_high_priority_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequestform',
            name='account_executive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequestform',
            name='legal_documentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequestform',
            name='most_senior_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequestform',
            name='relationship_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
