# Generated by Django 5.2.1 on 2025-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0023_allow_null_in_credit_request_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalreviewform',
            name='agreement_template',
            field=models.CharField(blank=True, help_text='Agreement template used (e.g., ISDA, CSA)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='counterparty_events_of_default',
            field=models.TextField(blank=True, help_text='Counterparty events of default provisions', null=True),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='csa_type',
            field=models.CharField(blank=True, help_text='Type of CSA agreement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='governing_law',
            field=models.CharField(blank=True, help_text='Governing law for the agreement', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='grace_period',
            field=models.CharField(blank=True, help_text='Grace period for defaults', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legalreviewform',
            name='non_standard_provisions',
            field=models.TextField(blank=True, help_text='Any non-standard provisions in the agreement', null=True),
        ),
    ]
