# Generated by Django 5.2.1 on 2025-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0024_allow_null_legal_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditanalysisform',
            name='business_model_assessment',
            field=models.TextField(blank=True, help_text='Assessment of business model and strategy', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='cash_flow_analysis',
            field=models.TextField(blank=True, help_text='Cash flow analysis and projections', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='credit_rating_recommendation',
            field=models.CharField(blank=True, help_text='Internal credit rating recommendation', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='debt_capacity_analysis',
            field=models.TextField(blank=True, help_text='Assessment of debt capacity and leverage', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='Executive summary of the credit analysis', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='industry_analysis',
            field=models.TextField(blank=True, help_text='Industry analysis and outlook', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='key_risks',
            field=models.TextField(blank=True, help_text='Key risks identified', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='management_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('poor', 'Poor')], help_text='Management quality assessment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='mitigating_factors',
            field=models.TextField(blank=True, help_text='Mitigating factors and risk controls', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='profitability_analysis',
            field=models.TextField(blank=True, help_text='Analysis of profitability metrics', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='revenue_analysis',
            field=models.TextField(blank=True, help_text='Analysis of revenue trends and sustainability', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='business_rationale',
            field=models.TextField(blank=True, help_text='Business rationale for the facilities', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='conditions_precedent',
            field=models.TextField(blank=True, help_text='Conditions precedent to drawdown', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='counterparty_background',
            field=models.TextField(blank=True, help_text='Background information on counterparty', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='credit_paper_summary',
            field=models.TextField(blank=True, help_text='Executive summary of the credit paper', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='facility_summary',
            field=models.TextField(blank=True, help_text='Summary of requested facilities', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='financial_analysis_summary',
            field=models.TextField(blank=True, help_text='Summary of financial analysis', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='legal_documentation_summary',
            field=models.TextField(blank=True, help_text='Summary of legal documentation review', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='ongoing_covenants',
            field=models.TextField(blank=True, help_text='Ongoing covenants and monitoring requirements', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='pricing_summary',
            field=models.TextField(blank=True, help_text='Pricing and fee structure summary', null=True),
        ),
        migrations.AlterField(
            model_name='creditcompilationform',
            name='risk_assessment_summary',
            field=models.TextField(blank=True, help_text='Summary of risk assessment findings', null=True),
        ),
    ]
