# Generated by Django 5.2.1 on 2025-12-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0025_allow_null_credit_analysis_compilation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditanalysisform',
            name='climate_risk_score',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Climate risk assessment score', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='esg_score',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='ESG risk score', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='physical_risk_assessment',
            field=models.TextField(blank=True, help_text='Assessment of physical climate risks', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('approve_with_conditions', 'Approve with Conditions'), ('reject', 'Reject')], help_text='Final recommendation', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='recommended_conditions',
            field=models.TextField(blank=True, help_text='Recommended conditions if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='creditanalysisform',
            name='transition_risk_assessment',
            field=models.TextField(blank=True, help_text='Assessment of transition risks', null=True),
        ),
    ]
