# Generated by Django 5.2.1 on 2025-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_applications', '0026_allow_null_remaining_credit_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcompilationform',
            name='compiler_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the compiler', null=True),
        ),
    ]
