# Generated by Django 5.2.1 on 2025-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='da_level',
            field=models.CharField(blank=True, choices=[('DA1', 'DA1'), ('DA2', 'DA2'), ('DA3', 'DA3'), ('DA4', 'DA4'), ('DA5', 'DA5'), ('DA6', 'DA6'), ('DA7', 'DA7'), ('DA8', 'DA8')], help_text='Delegated Authority level (DA1–DA8), only for Credit Approvers.', max_length=4, null=True),
        ),
    ]
