# Generated by Django 5.2.1 on 2025-06-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowDefinition',
            new_name='Workflow',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='workflow_definition',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='transition',
            old_name='workflow_definition',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='workflowinstance',
            old_name='workflow_definition',
            new_name='workflow',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('workflow', 'code')},
        ),
    ]
