# Generated by Codex on 2026-03-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_engine', '0002_rename_workflowdefinition_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_key', models.CharField(max_length=100)),
                ('artifact_kind', models.CharField(default='form', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='workflow_engine.workflowinstance')),
            ],
            options={
                'unique_together': {('workflow_instance', 'artifact_key')},
            },
        ),
    ]
